name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'who to greet'
        type: string
        required: true
        default: 'World'
    outputs:
      current-time:
        description: 'The greeting time'
        value: ${{ jobs.reusable_job.outputs.current-time }}
        
jobs:
  reusable_job:
    runs-on: ubuntu-latest
    outputs:
      current_time: ${{ steps.time.outputs.time }} 
    steps:
      - name: Greet somebody
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

